# Updates Satellite Servers to the next minor version.
#
# @SEE https://access.redhat.com/documentation/en-us/red_hat_satellite/6.2/html-single/installation_guide/#updating_satellite_server_to_next_minor_version

- name: Download updated packages
  command: yum update --downloadonly
  become: True

- name: Stop Katello
  command: katello-service stop
  become: True

- name: Update all packages
  yum:
    name: '*'
    state: latest
  become: True

- name: Reboot
  command: "shutdown --reboot +1 'Reboot invoked by Ansible'"
  register: redhat_reboot

- name: Wait for Host After Reboot
  wait_for:
    host: "{{ ansible_hostname }}"
    delay: 65
    port: 22
    state: started
  delegate_to: localhost
  become: False
  when: redhat_reboot.changed

- name: Upgrade Satellite Server
  command: satellite-installer --scenario satellite --upgrade
  become: True
  register: satellite_server_upgrade

- name: Restart goferd
  service:
    name: goferd
    state: restarted
  become: True
